### PR TITLE
p8-platform-config: fix lookup paths

### PR DESCRIPTION
**Pull request by yann-morin-1998**
Use the proper methods to find the headers and the library.

Signed-off-by: Samuel Martin <s.martin49@gmail.com>
Signed-off-by: "Yann E. MORIN" <yann.morin.1998@free.fr>

### CODE REVIEW

**Comment by yann-morin-1998** [comment]
Ping? ;-)

**Comment by yann-morin-1998** [comment]
Just a gentle reminder... ;-)

**Comment by opdenkamp** [comment]
Sorry for the late response. Just looking at this, but in which situation is this actually needed? I was just looking into the details of this cmake directive, but won't this pick up system libraries too, when you actually don't want those?

**Comment by yann-morin-1998** [comment]
As I remember from the context from back then, this is to fix cross-compilation.

We have had issues in Buildroot, where the p8-platform.cmake file, **once
installed**, would cause cmake to fail detection of p8-platform in libcec,
like so (only one such build failure, we had a lot of them):

http://autobuild.buildroot.org/results/052/052b29efb3e5b208003ea40aa6499297bbbb7ad4/build-end.log

The build error was a bit criptic, though, so I don't remember all the
details. But it boils down to the fact that libp8-platform is configured
with a standard /usr prefix, but installed out of tree. In that case,
the .cmake file will contain path that point to the host machine, not
the cross-headers, and cmake does not sanitise those paths because they
are used in a 'set' macro, which does just do what it is told to do,
without any processing whatsoever.

So, this patch just uses standard cmake constructs and documented
solution to find headers and libraries, which is guaranteed to work both
in native and cross compilation, because cmake will set the proper
CFLAGS (`-I`) and LDFLAGS (`-L` and `-l`) based on the path the .cmake
file was found.

Well, at least that's what the cmake doc says. Well, at least that's
what I understood of it, of course. ;-] Well, at least that's fixed our
issue, and we've been using it for the past 6 months-or-so without any
other trouble.

Thanks,
Regards.

**Comment by yann-morin-1998** [comment]
@opdenkamp Ping? ;-)

**Comment by opdenkamp** [comment]
Just looking at this repos too now, sorry for the delay.

**Pull request merged**
