### PR TITLE
fixed: set libdir on linux when CMAKE_INSTALL_PREFIX != /usr

### PR DESCRIPTION
**Pull request by wsnipex**
fix libdir after https://github.com/Pulse-Eight/platform/commit/2eca9d3f9bae2b3c5094f1242ee53fc9be0a9e7a

### CODE REVIEW

**Comment by nmvega** [comment]
Hi @wsnipex  (nice to see you here, too). =:)

I obtain the same error after your update.

By the way, I cloned this URL when retrying: https://github.com/Pulse-Eight/platform.git
Is this URL correct (or should I be retrying with a different URL/Branch)?

Thank you.

**Comment by wsnipex** [comment]
no, you either must apply the patch manually, or clone my repo: https://github.com/wsnipex/platform.git

**Comment by nmvega** [comment]
Hi @wsnipex 
ah, okay thank you. I'll clone your repository and let you know how it goes.
Will be in touche later on.

**Comment by wsnipex** [comment]
any feedback?

**Comment by nmvega** [comment]
H @wsnipex

Apologies for the delay. See below. Indeed your modifications fixed the issue. I will close the issue as solved. Thank you. =:)

====================================================
+ cmake -DCMAKE_INSTALL_PREFIX=/opt/KODI.d
-- The C compiler identification is GNU 4.8.3
[ ... snip ... ]
-- Performing Test HAS_BUILTIN_SYNC_VAL_COMPARE_AND_SWAP - Success
-- Configuring done
-- Generating done
-- Build files have been written to: .........[... snip ... ] /CURRENT.d/platform.d
+ make
Scanning dependencies of target platform
[ 50%] Building C object CMakeFiles/platform.dir/src/util/fstrcmp.c.o
[100%] Building CXX object CMakeFiles/platform.dir/src/util/StringUtils.cpp.o
Linking CXX static library libplatform.a
[100%] Built target platform

**Pull request merged**
