### PR TITLE
Simplify pkconfig file creation

### PR DESCRIPTION
**Pull request by rbalint**
Tested on Linux

### CODE REVIEW

**Comment by opdenkamp** [comment]
this is the same as is done in kodi-platform: https://github.com/xbmc/kodi-platform/blob/master/CMakeLists.txt#L53
never looked into it, but I can imagine that our fancy cross compile targets need something special again. @wsnipex do you have any idea why `configure_file()` wasn't used for this?

**Comment by wsnipex** [comment]
I don't know either and also didn't look into it in detail.
I guess @notspiff originally added it

**Comment by akva2** [comment]
I copied stuff from another project i work on. This should be fine here..

**Comment by rbalint** [comment]
I would love to see this thing simplified because I have several additional patches making the build system even more simple and those patches would build on this one.
Is there is something broken by the patch like cross-compiling I would happily help fixing it.

**Comment by akva2** [comment]
nothing should break, it was just lazyness that made me use what was at hand.

**Comment by wsnipex** [comment]
yes, looks fine for me too, but I didn't test it.

**Pull request merged**
