### PR TITLE
rename to p8-platform...

### PR DESCRIPTION
**Pull request by opdenkamp**
... to stop the debian folk from moaning ;-)

### CODE REVIEW

**Comment by wsnipex** [comment]
meh....  I told you right from the start
debian stuff needs something like
>Replaces: libplatform

**Comment by opdenkamp** [comment]
yeah debian...
as for the "Replaces" line, I kept that one out on purpose, so it doesn't break everything using it but that's not been upgraded yet.

**Comment by opdenkamp** [comment]
@wsnipex guess I'll change the namespace too to avoid collisions. then add-ons can keep using the current one and replace it later. will update the PR accordingly tonight

**Comment by opdenkamp** [comment]
right, so I've changed the name (directory), namespace and didn't use `Replaces`. That should allow the two to co-exist, so things using it should be able to upgrade without breaking others that haven't been upgraded yet.

sounds ok @wsnipex ? then I'll merge it in

**Comment by wsnipex** [comment]
looks good

**Comment by opdenkamp** [comment]
cool thanks

**Comment by Fneufneu** [comment]
Nice thank you for this one

**Pull request merged**
